package com.antaurora.apofirstlight.worldgen.highway;

public final class HighwayRenderStats {
    public int groundSegments;
    public int cutSegments;
    public int fillSegments;
    public int viaductSegments;
    public int tunnelSegments;
    public int blocksPlaced;
    public int blocksCleared;
    public int fillBlocks;
    public int cutBlocks;
    public int viaductBlocks;
    public int piersPlaced;
    public int corridorCellCount;
    public int expectedSurfaceCells;
    public int actualSurfaceCells;
    public int missingSurfaceCells;
    public int clearanceViolations;
    public int groundCells;
    public int cutCells;
    public int fillCells;
    public int viaductCells;
    public int tunnelCells;
    public int viaductDeckCells;
    public int viaductStructuralBlocks;
    public int rawViaductSamples;
    public int resolvedBridgeSpanCount;
    public int resolvedViaductStations;
    public int rawViaductLength;
    public int resolvedViaductLength;
    public int bridgeGapClosures;
    public int shortBridgeCandidatesRejected;
    public int maxCrossSlopeObserved;
    public double maxWaterCoverageObserved;
    public boolean extremeCrossSectionEncountered;
    public int pierStationsPlanned;
    public int piersSkipped;
    public int pierFoundationFailures;
    public int minPierHeight = Integer.MAX_VALUE;
    public int maxPierHeight;
    public int pierHeightTotal;
    public int waterPiers;
    public int landPiers;
    public int asphaltSurfaceBlocks;
    public int groundAsphaltSurfaceBlocks;
    public int cutAsphaltSurfaceBlocks;
    public int fillAsphaltSurfaceBlocks;
    public int viaductAsphaltSurfaceBlocks;
    public int tunnelAsphaltSurfaceBlocks;
    public int reinforcedConcreteBlocks;
    public int missingViaductDeckCells;
    public int wrongSurfaceMaterialCells;
    public int bridgeSpanInternalNonViaductCells;
    public int bridgeSpanNormalBaseIntrusions;
    public int airspaceClearanceViolations;
    public int remainingRowLogs;
    public int remainingRowLeaves;
    public int vegetationClearanceViolations;
    public int vegetationBlocksCleared;
    public int vegetationComponentsCleared;
    public int vegetationCleanupTruncated;
    public int floatingPierCount;
    public int structuralApproachStations;
    public int structuralApproachCells;
    public int structuralBridgeCells;
    public int bridgeApproachStartExtensions;
    public int bridgeApproachEndExtensions;
    public int bridgeApproachSupportFailures;
    public int elevatedNormalBaseIntrusions;
    public int expectedParapetBlocks;
    public int actualParapetBlocks;
    public int missingParapetBlocks;
    public int parapetSlabBlocks;
    public int medianBarrierBlocks;
    public int viaductOutsideStructuralBridgeCells;
    public int structuralBridgeMissingConcreteCells;
    public int cutColumnsPlanned;
    public int cutColumnsCleared;
    public int cutTerrainBlocksCleared;
    public int cutColumnsWithRemainingTerrainIntrusion;
    public int maxCutClearanceHeightObserved;
    public int terrainAirspaceViolations;
    public int unexpectedAirspaceObstructions;
    public int roadFurnitureBlocksIgnoredByAirspaceValidator;
    public int authoritativeSurfaceKeys;
    public int uniqueCoreRoadXZColumns;
    public int duplicateXZDifferentRoadYSurfaceKeys;
    public int coreRoadColumnsPlanned;
    public int coreRoadColumnsWithOriginalObstruction;
    public int coreRoadVerticalBlocksScanned;
    public int coreRoadVerticalBlocksCleared;
    public int coreRoadClearanceTruncatedColumns;
    public int coreRoadProtectedObstructionFailures;
    public int coreRoadTerrainIntrusions;
    public int nonFurnitureBlockDirectlyAboveSurface;
    public int preConstructionSnapshotColumns;
    public int snapshotColumnsMissing;
    public int snapshotBlockStatesScanned;
    public long snapshotCaptureNanos;
    public int naturalClearancePassRuns;
    public long clearancePassNanos;
    public int naturalCoreRoadColumnsChecked;
    public int rowColumnsChecked;
    public int airspaceColumnsChecked;
    public int remainingRowVegetation;
    public int naturalClearanceBlocksRemoved;
    public int naturalVegetationBlocksRemoved;
    public int naturalFloatingTerrainPrevented;
    public int legalInterchangeStructureBlocksIgnored;
    public int legalInterchangeStructureClearanceViolations;
    public int expectedWhiteEdgeMarkings;
    public int actualWhiteEdgeMarkings;
    public int missingWhiteEdgeMarkings;
    public int expectedYellowEdgeMarkings;
    public int actualYellowEdgeMarkings;
    public int missingYellowEdgeMarkings;
    public int expectedWhiteLaneDividerMarkings;
    public int actualWhiteLaneDividerMarkings;
    public int missingWhiteLaneDividerMarkings;
    public int laneDividerDashOnBlocks;
    public int laneDividerDashGapBlocks;
    public int unexpectedWhiteLaneDividerInGap;
    public int wrongMarkingTypeBlocks;
    public int markingsSkippedUnsupportedDiagonal;
    public int roadMarkingBlocksPlaced;
    public int roadStepTransitions;
    public int roadStepRiseTransitions;
    public int roadStepDropTransitions;
    public int expectedWhiteEdgeStepConnectors;
    public int actualWhiteEdgeStepConnectors;
    public int missingWhiteEdgeStepConnectors;
    public int expectedYellowEdgeStepConnectors;
    public int actualYellowEdgeStepConnectors;
    public int missingYellowEdgeStepConnectors;
    public int expectedLaneDividerStepConnectors;
    public int actualLaneDividerStepConnectors;
    public int missingLaneDividerStepConnectors;
    public int laneDividerStepConnectorSkipped;
    public int unexpectedLaneDividerStepConnectorInGap;
    public int wrongStepConnectorTypeBlocks;
    public int unsupportedMarkingStepHeight;
    public int stepConnectorBlocksPlaced;
    public int medianStepTransitions;
    public int medianStepRiseTransitions;
    public int medianStepDropTransitions;
    public int expectedMedianStepConnectors;
    public int actualMedianStepConnectors;
    public int missingMedianStepConnectors;
    public int wrongMedianStepConnectorTypeBlocks;
    public int unsupportedMedianStepHeight;
    public int medianStepConnectorBlocksPlaced;
    public int tunnelCandidateStations;
    public int tunnelQualifiedStations;
    public int tunnelRejectedShortSpanStations;
    public int tunnelRejectedLowCoverStations;
    public int tunnelRejectedSideExposureStations;
    public int tunnelRejectedWaterStations;
    public int tunnelRejectedViaductStations;
    public int rawTunnelSpanCount;
    public int resolvedTunnelSpanCount;
    public int tunnelGapClosures;
    public double minTunnelLength;
    public double maxTunnelLength;
    public double avgTunnelLength;
    public double minRockCoverObserved;
    public double maxRockCoverObserved;
    public double avgRockCoverObserved;
    public int normalTunnelCandidateStations;
    public int promotedTunnelCandidateStations;
    public int deepCutStationsEvaluated;
    public int deepCutPromotionCandidates;
    public int deepCutPromotedStations;
    public int deepCutPromotedSpans;
    public int deepCutRejectedTooShort;
    public int deepCutRejectedTooOpen;
    public int deepCutRejectedLowCover;
    public int deepCutGapClosures;
    public int deepCutPortalAdjustments;
    public long deepCutEvaluationNanos;
    public int portalCount;
    public int portalStartCount;
    public int portalEndCount;
    public int portalInsetAdjustments;
    public int portalPlacementFailures;
    public int tunnelInteriorStations;
    public int tunnelPortalStations;
    public int tunnelRoofOpenToSkyViolations;
    public int tunnelInteriorObstructionCells;
    public int expectedTunnelLiningBlocks;
    public int actualTunnelLiningBlocks;
    public int missingTunnelLiningBlocks;
    public int expectedPortalBlocks;
    public int actualPortalBlocks;
    public int missingPortalBlocks;
    public int tunnelStationsTouchedByOpenSkyClearance;
    public int openSkyClearanceBypassedTunnelStations;
    public int tunnelInteriorBlocksCleared;
    public int tunnelLiningBlocksPlaced;
    public int portalBlocksPlaced;
    public int tunnelInteriorWidth;
    public int tunnelInteriorHeight;
    public int tunnelOuterWidth;
    public int tunnelOuterHeight;

    public void addCellMode(HighwayTerrainMode mode) {
        switch (mode) {
            case GROUND -> groundCells++;
            case CUT -> cutCells++;
            case FILL -> fillCells++;
            case VIADUCT -> viaductCells++;
            case TUNNEL -> tunnelCells++;
        }
    }

    public void addMode(HighwayTerrainMode mode) {
        switch (mode) {
            case GROUND -> groundSegments++;
            case CUT -> cutSegments++;
            case FILL -> fillSegments++;
            case VIADUCT -> viaductSegments++;
            case TUNNEL -> tunnelSegments++;
        }
    }

    public void add(HighwayRenderStats other) {
        groundSegments += other.groundSegments;
        cutSegments += other.cutSegments;
        fillSegments += other.fillSegments;
        viaductSegments += other.viaductSegments;
        tunnelSegments += other.tunnelSegments;
        blocksPlaced += other.blocksPlaced;
        blocksCleared += other.blocksCleared;
        fillBlocks += other.fillBlocks;
        cutBlocks += other.cutBlocks;
        viaductBlocks += other.viaductBlocks;
        piersPlaced += other.piersPlaced;
        corridorCellCount += other.corridorCellCount;
        expectedSurfaceCells += other.expectedSurfaceCells;
        actualSurfaceCells += other.actualSurfaceCells;
        missingSurfaceCells += other.missingSurfaceCells;
        clearanceViolations += other.clearanceViolations;
        groundCells += other.groundCells;
        cutCells += other.cutCells;
        fillCells += other.fillCells;
        viaductCells += other.viaductCells;
        tunnelCells += other.tunnelCells;
        viaductDeckCells += other.viaductDeckCells;
        viaductStructuralBlocks += other.viaductStructuralBlocks;
        rawViaductSamples += other.rawViaductSamples;
        resolvedBridgeSpanCount += other.resolvedBridgeSpanCount;
        resolvedViaductStations += other.resolvedViaductStations;
        rawViaductLength += other.rawViaductLength;
        resolvedViaductLength += other.resolvedViaductLength;
        bridgeGapClosures += other.bridgeGapClosures;
        shortBridgeCandidatesRejected += other.shortBridgeCandidatesRejected;
        maxCrossSlopeObserved = Math.max(maxCrossSlopeObserved, other.maxCrossSlopeObserved);
        maxWaterCoverageObserved = Math.max(maxWaterCoverageObserved, other.maxWaterCoverageObserved);
        extremeCrossSectionEncountered |= other.extremeCrossSectionEncountered;
        pierStationsPlanned += other.pierStationsPlanned;
        piersSkipped += other.piersSkipped;
        pierFoundationFailures += other.pierFoundationFailures;
        minPierHeight = Math.min(minPierHeight, other.minPierHeight);
        maxPierHeight = Math.max(maxPierHeight, other.maxPierHeight);
        pierHeightTotal += other.pierHeightTotal;
        waterPiers += other.waterPiers;
        landPiers += other.landPiers;
        asphaltSurfaceBlocks += other.asphaltSurfaceBlocks;
        groundAsphaltSurfaceBlocks += other.groundAsphaltSurfaceBlocks;
        cutAsphaltSurfaceBlocks += other.cutAsphaltSurfaceBlocks;
        fillAsphaltSurfaceBlocks += other.fillAsphaltSurfaceBlocks;
        viaductAsphaltSurfaceBlocks += other.viaductAsphaltSurfaceBlocks;
        tunnelAsphaltSurfaceBlocks += other.tunnelAsphaltSurfaceBlocks;
        reinforcedConcreteBlocks += other.reinforcedConcreteBlocks;
        missingViaductDeckCells += other.missingViaductDeckCells;
        wrongSurfaceMaterialCells += other.wrongSurfaceMaterialCells;
        bridgeSpanInternalNonViaductCells += other.bridgeSpanInternalNonViaductCells;
        bridgeSpanNormalBaseIntrusions += other.bridgeSpanNormalBaseIntrusions;
        airspaceClearanceViolations += other.airspaceClearanceViolations;
        remainingRowLogs += other.remainingRowLogs;
        remainingRowLeaves += other.remainingRowLeaves;
        vegetationClearanceViolations += other.vegetationClearanceViolations;
        vegetationBlocksCleared += other.vegetationBlocksCleared;
        vegetationComponentsCleared += other.vegetationComponentsCleared;
        vegetationCleanupTruncated += other.vegetationCleanupTruncated;
        floatingPierCount += other.floatingPierCount;
        structuralApproachStations += other.structuralApproachStations;
        structuralApproachCells += other.structuralApproachCells;
        structuralBridgeCells += other.structuralBridgeCells;
        bridgeApproachStartExtensions += other.bridgeApproachStartExtensions;
        bridgeApproachEndExtensions += other.bridgeApproachEndExtensions;
        bridgeApproachSupportFailures += other.bridgeApproachSupportFailures;
        elevatedNormalBaseIntrusions += other.elevatedNormalBaseIntrusions;
        expectedParapetBlocks += other.expectedParapetBlocks;
        actualParapetBlocks += other.actualParapetBlocks;
        missingParapetBlocks += other.missingParapetBlocks;
        parapetSlabBlocks += other.parapetSlabBlocks;
        medianBarrierBlocks += other.medianBarrierBlocks;
        viaductOutsideStructuralBridgeCells += other.viaductOutsideStructuralBridgeCells;
        structuralBridgeMissingConcreteCells += other.structuralBridgeMissingConcreteCells;
        cutColumnsPlanned += other.cutColumnsPlanned;
        cutColumnsCleared += other.cutColumnsCleared;
        cutTerrainBlocksCleared += other.cutTerrainBlocksCleared;
        cutColumnsWithRemainingTerrainIntrusion += other.cutColumnsWithRemainingTerrainIntrusion;
        maxCutClearanceHeightObserved = Math.max(maxCutClearanceHeightObserved,
                other.maxCutClearanceHeightObserved);
        terrainAirspaceViolations += other.terrainAirspaceViolations;
        unexpectedAirspaceObstructions += other.unexpectedAirspaceObstructions;
        roadFurnitureBlocksIgnoredByAirspaceValidator +=
                other.roadFurnitureBlocksIgnoredByAirspaceValidator;
        authoritativeSurfaceKeys += other.authoritativeSurfaceKeys;
        uniqueCoreRoadXZColumns += other.uniqueCoreRoadXZColumns;
        duplicateXZDifferentRoadYSurfaceKeys += other.duplicateXZDifferentRoadYSurfaceKeys;
        coreRoadColumnsPlanned += other.coreRoadColumnsPlanned;
        coreRoadColumnsWithOriginalObstruction += other.coreRoadColumnsWithOriginalObstruction;
        coreRoadVerticalBlocksScanned += other.coreRoadVerticalBlocksScanned;
        coreRoadVerticalBlocksCleared += other.coreRoadVerticalBlocksCleared;
        coreRoadClearanceTruncatedColumns += other.coreRoadClearanceTruncatedColumns;
        coreRoadProtectedObstructionFailures += other.coreRoadProtectedObstructionFailures;
        coreRoadTerrainIntrusions += other.coreRoadTerrainIntrusions;
        nonFurnitureBlockDirectlyAboveSurface += other.nonFurnitureBlockDirectlyAboveSurface;
        preConstructionSnapshotColumns += other.preConstructionSnapshotColumns;
        snapshotColumnsMissing += other.snapshotColumnsMissing;
        snapshotBlockStatesScanned += other.snapshotBlockStatesScanned;
        snapshotCaptureNanos += other.snapshotCaptureNanos;
        naturalClearancePassRuns += other.naturalClearancePassRuns;
        clearancePassNanos += other.clearancePassNanos;
        naturalCoreRoadColumnsChecked += other.naturalCoreRoadColumnsChecked;
        rowColumnsChecked += other.rowColumnsChecked;
        airspaceColumnsChecked += other.airspaceColumnsChecked;
        remainingRowVegetation += other.remainingRowVegetation;
        naturalClearanceBlocksRemoved += other.naturalClearanceBlocksRemoved;
        naturalVegetationBlocksRemoved += other.naturalVegetationBlocksRemoved;
        naturalFloatingTerrainPrevented += other.naturalFloatingTerrainPrevented;
        legalInterchangeStructureBlocksIgnored += other.legalInterchangeStructureBlocksIgnored;
        legalInterchangeStructureClearanceViolations += other.legalInterchangeStructureClearanceViolations;
        expectedWhiteEdgeMarkings += other.expectedWhiteEdgeMarkings;
        actualWhiteEdgeMarkings += other.actualWhiteEdgeMarkings;
        missingWhiteEdgeMarkings += other.missingWhiteEdgeMarkings;
        expectedYellowEdgeMarkings += other.expectedYellowEdgeMarkings;
        actualYellowEdgeMarkings += other.actualYellowEdgeMarkings;
        missingYellowEdgeMarkings += other.missingYellowEdgeMarkings;
        expectedWhiteLaneDividerMarkings += other.expectedWhiteLaneDividerMarkings;
        actualWhiteLaneDividerMarkings += other.actualWhiteLaneDividerMarkings;
        missingWhiteLaneDividerMarkings += other.missingWhiteLaneDividerMarkings;
        laneDividerDashOnBlocks += other.laneDividerDashOnBlocks;
        laneDividerDashGapBlocks += other.laneDividerDashGapBlocks;
        unexpectedWhiteLaneDividerInGap += other.unexpectedWhiteLaneDividerInGap;
        wrongMarkingTypeBlocks += other.wrongMarkingTypeBlocks;
        markingsSkippedUnsupportedDiagonal += other.markingsSkippedUnsupportedDiagonal;
        roadMarkingBlocksPlaced += other.roadMarkingBlocksPlaced;
        roadStepTransitions += other.roadStepTransitions;
        roadStepRiseTransitions += other.roadStepRiseTransitions;
        roadStepDropTransitions += other.roadStepDropTransitions;
        expectedWhiteEdgeStepConnectors += other.expectedWhiteEdgeStepConnectors;
        actualWhiteEdgeStepConnectors += other.actualWhiteEdgeStepConnectors;
        missingWhiteEdgeStepConnectors += other.missingWhiteEdgeStepConnectors;
        expectedYellowEdgeStepConnectors += other.expectedYellowEdgeStepConnectors;
        actualYellowEdgeStepConnectors += other.actualYellowEdgeStepConnectors;
        missingYellowEdgeStepConnectors += other.missingYellowEdgeStepConnectors;
        expectedLaneDividerStepConnectors += other.expectedLaneDividerStepConnectors;
        actualLaneDividerStepConnectors += other.actualLaneDividerStepConnectors;
        missingLaneDividerStepConnectors += other.missingLaneDividerStepConnectors;
        laneDividerStepConnectorSkipped += other.laneDividerStepConnectorSkipped;
        unexpectedLaneDividerStepConnectorInGap += other.unexpectedLaneDividerStepConnectorInGap;
        wrongStepConnectorTypeBlocks += other.wrongStepConnectorTypeBlocks;
        unsupportedMarkingStepHeight += other.unsupportedMarkingStepHeight;
        stepConnectorBlocksPlaced += other.stepConnectorBlocksPlaced;
        medianStepTransitions += other.medianStepTransitions;
        medianStepRiseTransitions += other.medianStepRiseTransitions;
        medianStepDropTransitions += other.medianStepDropTransitions;
        expectedMedianStepConnectors += other.expectedMedianStepConnectors;
        actualMedianStepConnectors += other.actualMedianStepConnectors;
        missingMedianStepConnectors += other.missingMedianStepConnectors;
        wrongMedianStepConnectorTypeBlocks += other.wrongMedianStepConnectorTypeBlocks;
        unsupportedMedianStepHeight += other.unsupportedMedianStepHeight;
        medianStepConnectorBlocksPlaced += other.medianStepConnectorBlocksPlaced;
        tunnelCandidateStations += other.tunnelCandidateStations;
        tunnelQualifiedStations += other.tunnelQualifiedStations;
        tunnelRejectedShortSpanStations += other.tunnelRejectedShortSpanStations;
        tunnelRejectedLowCoverStations += other.tunnelRejectedLowCoverStations;
        tunnelRejectedSideExposureStations += other.tunnelRejectedSideExposureStations;
        tunnelRejectedWaterStations += other.tunnelRejectedWaterStations;
        tunnelRejectedViaductStations += other.tunnelRejectedViaductStations;
        rawTunnelSpanCount += other.rawTunnelSpanCount;
        resolvedTunnelSpanCount += other.resolvedTunnelSpanCount;
        tunnelGapClosures += other.tunnelGapClosures;
        minTunnelLength = mergeMin(minTunnelLength, other.minTunnelLength);
        maxTunnelLength = Math.max(maxTunnelLength, other.maxTunnelLength);
        avgTunnelLength += other.avgTunnelLength;
        minRockCoverObserved = mergeMin(minRockCoverObserved, other.minRockCoverObserved);
        maxRockCoverObserved = Math.max(maxRockCoverObserved, other.maxRockCoverObserved);
        avgRockCoverObserved += other.avgRockCoverObserved;
        normalTunnelCandidateStations += other.normalTunnelCandidateStations;
        promotedTunnelCandidateStations += other.promotedTunnelCandidateStations;
        deepCutStationsEvaluated += other.deepCutStationsEvaluated;
        deepCutPromotionCandidates += other.deepCutPromotionCandidates;
        deepCutPromotedStations += other.deepCutPromotedStations;
        deepCutPromotedSpans += other.deepCutPromotedSpans;
        deepCutRejectedTooShort += other.deepCutRejectedTooShort;
        deepCutRejectedTooOpen += other.deepCutRejectedTooOpen;
        deepCutRejectedLowCover += other.deepCutRejectedLowCover;
        deepCutGapClosures += other.deepCutGapClosures;
        deepCutPortalAdjustments += other.deepCutPortalAdjustments;
        deepCutEvaluationNanos += other.deepCutEvaluationNanos;
        portalCount += other.portalCount;
        portalStartCount += other.portalStartCount;
        portalEndCount += other.portalEndCount;
        portalInsetAdjustments += other.portalInsetAdjustments;
        portalPlacementFailures += other.portalPlacementFailures;
        tunnelInteriorStations += other.tunnelInteriorStations;
        tunnelPortalStations += other.tunnelPortalStations;
        tunnelRoofOpenToSkyViolations += other.tunnelRoofOpenToSkyViolations;
        tunnelInteriorObstructionCells += other.tunnelInteriorObstructionCells;
        expectedTunnelLiningBlocks += other.expectedTunnelLiningBlocks;
        actualTunnelLiningBlocks += other.actualTunnelLiningBlocks;
        missingTunnelLiningBlocks += other.missingTunnelLiningBlocks;
        expectedPortalBlocks += other.expectedPortalBlocks;
        actualPortalBlocks += other.actualPortalBlocks;
        missingPortalBlocks += other.missingPortalBlocks;
        tunnelStationsTouchedByOpenSkyClearance += other.tunnelStationsTouchedByOpenSkyClearance;
        openSkyClearanceBypassedTunnelStations += other.openSkyClearanceBypassedTunnelStations;
        tunnelInteriorBlocksCleared += other.tunnelInteriorBlocksCleared;
        tunnelLiningBlocksPlaced += other.tunnelLiningBlocksPlaced;
        portalBlocksPlaced += other.portalBlocksPlaced;
        tunnelInteriorWidth = Math.max(tunnelInteriorWidth, other.tunnelInteriorWidth);
        tunnelInteriorHeight = Math.max(tunnelInteriorHeight, other.tunnelInteriorHeight);
        tunnelOuterWidth = Math.max(tunnelOuterWidth, other.tunnelOuterWidth);
        tunnelOuterHeight = Math.max(tunnelOuterHeight, other.tunnelOuterHeight);
    }

    private static double mergeMin(double current, double other) {
        if (current == 0.0) return other;
        if (other == 0.0) return current;
        return Math.min(current, other);
    }
}
