package com.antaurora.apofirstlight.worldgen.highway;

public final class HighwayRenderStats {
    public int groundSegments;
    public int cutSegments;
    public int fillSegments;
    public int viaductSegments;
    public int blocksPlaced;
    public int blocksCleared;
    public int fillBlocks;
    public int cutBlocks;
    public int viaductBlocks;
    public int piersPlaced;
    public int corridorCellCount;
    public int expectedSurfaceCells;
    public int actualSurfaceCells;
    public int missingSurfaceCells;
    public int clearanceViolations;
    public int groundCells;
    public int cutCells;
    public int fillCells;
    public int viaductCells;
    public int viaductDeckCells;
    public int viaductStructuralBlocks;
    public int rawViaductSamples;
    public int resolvedBridgeSpanCount;
    public int resolvedViaductStations;
    public int rawViaductLength;
    public int resolvedViaductLength;
    public int bridgeGapClosures;
    public int shortBridgeCandidatesRejected;
    public int maxCrossSlopeObserved;
    public double maxWaterCoverageObserved;
    public boolean extremeCrossSectionEncountered;
    public int pierStationsPlanned;
    public int piersSkipped;
    public int pierFoundationFailures;
    public int minPierHeight = Integer.MAX_VALUE;
    public int maxPierHeight;
    public int pierHeightTotal;
    public int waterPiers;
    public int landPiers;
    public int asphaltSurfaceBlocks;
    public int groundAsphaltSurfaceBlocks;
    public int cutAsphaltSurfaceBlocks;
    public int fillAsphaltSurfaceBlocks;
    public int viaductAsphaltSurfaceBlocks;
    public int reinforcedConcreteBlocks;
    public int missingViaductDeckCells;
    public int wrongSurfaceMaterialCells;
    public int bridgeSpanInternalNonViaductCells;
    public int bridgeSpanNormalBaseIntrusions;
    public int airspaceClearanceViolations;
    public int remainingRowLogs;
    public int remainingRowLeaves;
    public int vegetationClearanceViolations;
    public int vegetationBlocksCleared;
    public int vegetationComponentsCleared;
    public int vegetationCleanupTruncated;
    public int floatingPierCount;
    public int structuralApproachStations;
    public int structuralApproachCells;
    public int structuralBridgeCells;
    public int bridgeApproachStartExtensions;
    public int bridgeApproachEndExtensions;
    public int bridgeApproachSupportFailures;
    public int elevatedNormalBaseIntrusions;
    public int expectedParapetBlocks;
    public int actualParapetBlocks;
    public int missingParapetBlocks;
    public int parapetSlabBlocks;
    public int medianBarrierBlocks;
    public int viaductOutsideStructuralBridgeCells;
    public int structuralBridgeMissingConcreteCells;
    public int cutColumnsPlanned;
    public int cutColumnsCleared;
    public int cutTerrainBlocksCleared;
    public int cutColumnsWithRemainingTerrainIntrusion;
    public int maxCutClearanceHeightObserved;
    public int terrainAirspaceViolations;
    public int unexpectedAirspaceObstructions;
    public int roadFurnitureBlocksIgnoredByAirspaceValidator;
    public int authoritativeSurfaceKeys;
    public int uniqueCoreRoadXZColumns;
    public int duplicateXZDifferentRoadYSurfaceKeys;
    public int coreRoadColumnsPlanned;
    public int coreRoadColumnsWithOriginalObstruction;
    public int coreRoadVerticalBlocksScanned;
    public int coreRoadVerticalBlocksCleared;
    public int coreRoadClearanceTruncatedColumns;
    public int coreRoadProtectedObstructionFailures;
    public int coreRoadTerrainIntrusions;
    public int nonFurnitureBlockDirectlyAboveSurface;
    public int expectedWhiteEdgeMarkings;
    public int actualWhiteEdgeMarkings;
    public int missingWhiteEdgeMarkings;
    public int expectedYellowEdgeMarkings;
    public int actualYellowEdgeMarkings;
    public int missingYellowEdgeMarkings;
    public int expectedWhiteLaneDividerMarkings;
    public int actualWhiteLaneDividerMarkings;
    public int missingWhiteLaneDividerMarkings;
    public int wrongMarkingTypeBlocks;
    public int markingsSkippedUnsupportedDiagonal;
    public int roadMarkingBlocksPlaced;
    public int roadStepTransitions;
    public int roadStepRiseTransitions;
    public int roadStepDropTransitions;
    public int expectedWhiteEdgeStepConnectors;
    public int actualWhiteEdgeStepConnectors;
    public int missingWhiteEdgeStepConnectors;
    public int expectedYellowEdgeStepConnectors;
    public int actualYellowEdgeStepConnectors;
    public int missingYellowEdgeStepConnectors;
    public int expectedLaneDividerStepConnectors;
    public int actualLaneDividerStepConnectors;
    public int missingLaneDividerStepConnectors;
    public int laneDividerStepConnectorSkipped;
    public int wrongStepConnectorTypeBlocks;
    public int unsupportedMarkingStepHeight;
    public int stepConnectorBlocksPlaced;

    public void addCellMode(HighwayTerrainMode mode) {
        switch (mode) {
            case GROUND -> groundCells++;
            case CUT -> cutCells++;
            case FILL -> fillCells++;
            case VIADUCT -> viaductCells++;
        }
    }

    public void addMode(HighwayTerrainMode mode) {
        switch (mode) {
            case GROUND -> groundSegments++;
            case CUT -> cutSegments++;
            case FILL -> fillSegments++;
            case VIADUCT -> viaductSegments++;
        }
    }

    public void add(HighwayRenderStats other) {
        groundSegments += other.groundSegments;
        cutSegments += other.cutSegments;
        fillSegments += other.fillSegments;
        viaductSegments += other.viaductSegments;
        blocksPlaced += other.blocksPlaced;
        blocksCleared += other.blocksCleared;
        fillBlocks += other.fillBlocks;
        cutBlocks += other.cutBlocks;
        viaductBlocks += other.viaductBlocks;
        piersPlaced += other.piersPlaced;
        corridorCellCount += other.corridorCellCount;
        expectedSurfaceCells += other.expectedSurfaceCells;
        actualSurfaceCells += other.actualSurfaceCells;
        missingSurfaceCells += other.missingSurfaceCells;
        clearanceViolations += other.clearanceViolations;
        groundCells += other.groundCells;
        cutCells += other.cutCells;
        fillCells += other.fillCells;
        viaductCells += other.viaductCells;
        viaductDeckCells += other.viaductDeckCells;
        viaductStructuralBlocks += other.viaductStructuralBlocks;
        rawViaductSamples += other.rawViaductSamples;
        resolvedBridgeSpanCount += other.resolvedBridgeSpanCount;
        resolvedViaductStations += other.resolvedViaductStations;
        rawViaductLength += other.rawViaductLength;
        resolvedViaductLength += other.resolvedViaductLength;
        bridgeGapClosures += other.bridgeGapClosures;
        shortBridgeCandidatesRejected += other.shortBridgeCandidatesRejected;
        maxCrossSlopeObserved = Math.max(maxCrossSlopeObserved, other.maxCrossSlopeObserved);
        maxWaterCoverageObserved = Math.max(maxWaterCoverageObserved, other.maxWaterCoverageObserved);
        extremeCrossSectionEncountered |= other.extremeCrossSectionEncountered;
        pierStationsPlanned += other.pierStationsPlanned;
        piersSkipped += other.piersSkipped;
        pierFoundationFailures += other.pierFoundationFailures;
        minPierHeight = Math.min(minPierHeight, other.minPierHeight);
        maxPierHeight = Math.max(maxPierHeight, other.maxPierHeight);
        pierHeightTotal += other.pierHeightTotal;
        waterPiers += other.waterPiers;
        landPiers += other.landPiers;
        asphaltSurfaceBlocks += other.asphaltSurfaceBlocks;
        groundAsphaltSurfaceBlocks += other.groundAsphaltSurfaceBlocks;
        cutAsphaltSurfaceBlocks += other.cutAsphaltSurfaceBlocks;
        fillAsphaltSurfaceBlocks += other.fillAsphaltSurfaceBlocks;
        viaductAsphaltSurfaceBlocks += other.viaductAsphaltSurfaceBlocks;
        reinforcedConcreteBlocks += other.reinforcedConcreteBlocks;
        missingViaductDeckCells += other.missingViaductDeckCells;
        wrongSurfaceMaterialCells += other.wrongSurfaceMaterialCells;
        bridgeSpanInternalNonViaductCells += other.bridgeSpanInternalNonViaductCells;
        bridgeSpanNormalBaseIntrusions += other.bridgeSpanNormalBaseIntrusions;
        airspaceClearanceViolations += other.airspaceClearanceViolations;
        remainingRowLogs += other.remainingRowLogs;
        remainingRowLeaves += other.remainingRowLeaves;
        vegetationClearanceViolations += other.vegetationClearanceViolations;
        vegetationBlocksCleared += other.vegetationBlocksCleared;
        vegetationComponentsCleared += other.vegetationComponentsCleared;
        vegetationCleanupTruncated += other.vegetationCleanupTruncated;
        floatingPierCount += other.floatingPierCount;
        structuralApproachStations += other.structuralApproachStations;
        structuralApproachCells += other.structuralApproachCells;
        structuralBridgeCells += other.structuralBridgeCells;
        bridgeApproachStartExtensions += other.bridgeApproachStartExtensions;
        bridgeApproachEndExtensions += other.bridgeApproachEndExtensions;
        bridgeApproachSupportFailures += other.bridgeApproachSupportFailures;
        elevatedNormalBaseIntrusions += other.elevatedNormalBaseIntrusions;
        expectedParapetBlocks += other.expectedParapetBlocks;
        actualParapetBlocks += other.actualParapetBlocks;
        missingParapetBlocks += other.missingParapetBlocks;
        parapetSlabBlocks += other.parapetSlabBlocks;
        medianBarrierBlocks += other.medianBarrierBlocks;
        viaductOutsideStructuralBridgeCells += other.viaductOutsideStructuralBridgeCells;
        structuralBridgeMissingConcreteCells += other.structuralBridgeMissingConcreteCells;
        cutColumnsPlanned += other.cutColumnsPlanned;
        cutColumnsCleared += other.cutColumnsCleared;
        cutTerrainBlocksCleared += other.cutTerrainBlocksCleared;
        cutColumnsWithRemainingTerrainIntrusion += other.cutColumnsWithRemainingTerrainIntrusion;
        maxCutClearanceHeightObserved = Math.max(maxCutClearanceHeightObserved,
                other.maxCutClearanceHeightObserved);
        terrainAirspaceViolations += other.terrainAirspaceViolations;
        unexpectedAirspaceObstructions += other.unexpectedAirspaceObstructions;
        roadFurnitureBlocksIgnoredByAirspaceValidator +=
                other.roadFurnitureBlocksIgnoredByAirspaceValidator;
        authoritativeSurfaceKeys += other.authoritativeSurfaceKeys;
        uniqueCoreRoadXZColumns += other.uniqueCoreRoadXZColumns;
        duplicateXZDifferentRoadYSurfaceKeys += other.duplicateXZDifferentRoadYSurfaceKeys;
        coreRoadColumnsPlanned += other.coreRoadColumnsPlanned;
        coreRoadColumnsWithOriginalObstruction += other.coreRoadColumnsWithOriginalObstruction;
        coreRoadVerticalBlocksScanned += other.coreRoadVerticalBlocksScanned;
        coreRoadVerticalBlocksCleared += other.coreRoadVerticalBlocksCleared;
        coreRoadClearanceTruncatedColumns += other.coreRoadClearanceTruncatedColumns;
        coreRoadProtectedObstructionFailures += other.coreRoadProtectedObstructionFailures;
        coreRoadTerrainIntrusions += other.coreRoadTerrainIntrusions;
        nonFurnitureBlockDirectlyAboveSurface += other.nonFurnitureBlockDirectlyAboveSurface;
        expectedWhiteEdgeMarkings += other.expectedWhiteEdgeMarkings;
        actualWhiteEdgeMarkings += other.actualWhiteEdgeMarkings;
        missingWhiteEdgeMarkings += other.missingWhiteEdgeMarkings;
        expectedYellowEdgeMarkings += other.expectedYellowEdgeMarkings;
        actualYellowEdgeMarkings += other.actualYellowEdgeMarkings;
        missingYellowEdgeMarkings += other.missingYellowEdgeMarkings;
        expectedWhiteLaneDividerMarkings += other.expectedWhiteLaneDividerMarkings;
        actualWhiteLaneDividerMarkings += other.actualWhiteLaneDividerMarkings;
        missingWhiteLaneDividerMarkings += other.missingWhiteLaneDividerMarkings;
        wrongMarkingTypeBlocks += other.wrongMarkingTypeBlocks;
        markingsSkippedUnsupportedDiagonal += other.markingsSkippedUnsupportedDiagonal;
        roadMarkingBlocksPlaced += other.roadMarkingBlocksPlaced;
        roadStepTransitions += other.roadStepTransitions;
        roadStepRiseTransitions += other.roadStepRiseTransitions;
        roadStepDropTransitions += other.roadStepDropTransitions;
        expectedWhiteEdgeStepConnectors += other.expectedWhiteEdgeStepConnectors;
        actualWhiteEdgeStepConnectors += other.actualWhiteEdgeStepConnectors;
        missingWhiteEdgeStepConnectors += other.missingWhiteEdgeStepConnectors;
        expectedYellowEdgeStepConnectors += other.expectedYellowEdgeStepConnectors;
        actualYellowEdgeStepConnectors += other.actualYellowEdgeStepConnectors;
        missingYellowEdgeStepConnectors += other.missingYellowEdgeStepConnectors;
        expectedLaneDividerStepConnectors += other.expectedLaneDividerStepConnectors;
        actualLaneDividerStepConnectors += other.actualLaneDividerStepConnectors;
        missingLaneDividerStepConnectors += other.missingLaneDividerStepConnectors;
        laneDividerStepConnectorSkipped += other.laneDividerStepConnectorSkipped;
        wrongStepConnectorTypeBlocks += other.wrongStepConnectorTypeBlocks;
        unsupportedMarkingStepHeight += other.unsupportedMarkingStepHeight;
        stepConnectorBlocksPlaced += other.stepConnectorBlocksPlaced;
    }
}
